-- ============================================================
-- STUDY PLANNER v17 - ONE COMPLETE SQL SCRIPT
-- ============================================================
-- Freshly compatible with the existing database used in the project.
-- It keeps existing data, adds missing columns, and installs the
-- complete admin + planning RPC layer.
--
-- Default admin after running this script:
-- username: admin
-- password: admin
-- No password complexity rule is enforced.
-- ============================================================

create extension if not exists pgcrypto with schema extensions;

-- ============================================================
-- 1) CORE TABLES
-- ============================================================

create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.courses_v2 (
  id bigint generated by default as identity primary key,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  title text not null,
  professor text,
  drive_url text,
  sort_order integer not null default 1,
  global_order integer,
  created_at timestamptz not null default now()
);

alter table public.courses_v2 add column if not exists drive_url text;
alter table public.courses_v2 add column if not exists global_order integer;
alter table public.courses_v2 add column if not exists planned_days integer not null default 1;
alter table public.courses_v2 add column if not exists default_duration_min integer not null default 90;
alter table public.courses_v2 add column if not exists default_notes text;

create table if not exists public.study_sessions_v2 (
  id uuid primary key default gen_random_uuid(),
  course_id bigint not null references public.courses_v2(id) on delete cascade,
  study_date date not null,
  mode text not null default 'online' check (mode in ('online','offline')),
  duration_min integer not null default 90 check (duration_min >= 0),
  notes text,
  planned_days integer not null default 1 check (planned_days >= 1),
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.planner_settings (
  id integer primary key,
  start_date date not null default date '2026-09-17',
  offline_day integer not null default 0,
  allow_weekends boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.planner_settings add column if not exists offline_day integer not null default 0;
alter table public.planner_settings add column if not exists allow_weekends boolean not null default true;
alter table public.planner_settings add column if not exists updated_at timestamptz not null default now();

create table if not exists public.admin_config (
  id integer primary key,
  username text not null,
  password_hash text not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_sessions (
  token text primary key,
  expires_at timestamptz not null
);

-- ============================================================
-- 2) INITIAL / EXISTING DATA REPAIR
-- ============================================================

-- Default subject if none exists.
insert into public.subjects(name, sort_order)
select 'Gynécologie-obstétrique', 1
where not exists (select 1 from public.subjects);

-- Backfill global_order for any old courses that do not have one.
with ranked as (
  select
    c.id,
    row_number() over (
      order by
        coalesce(s.sort_order, 999999),
        coalesce(c.sort_order, 999999),
        c.id
    ) as rn
  from public.courses_v2 c
  left join public.subjects s on s.id = c.subject_id
  where c.global_order is null
)
update public.courses_v2 c
set global_order = ranked.rn
from ranked
where c.id = ranked.id;

-- Normalize the complete global order so every course has a unique position.
with normalized as (
  select id, row_number() over (order by global_order nulls last, id) as rn
  from public.courses_v2
)
update public.courses_v2 c
set global_order = normalized.rn
from normalized
where c.id = normalized.id;

-- Persist the current planning metadata at course level.
with meta as (
  select
    c.id,
    greatest(1, coalesce(max(s.planned_days), c.planned_days, 1)) as days,
    greatest(0, coalesce(max(s.duration_min), c.default_duration_min, 90)) as duration_min,
    max(s.notes) as notes
  from public.courses_v2 c
  left join public.study_sessions_v2 s on s.course_id = c.id
  group by c.id, c.planned_days, c.default_duration_min
)
update public.courses_v2 c
set planned_days = meta.days,
    default_duration_min = meta.duration_min,
    default_notes = coalesce(meta.notes, c.default_notes)
from meta
where c.id = meta.id;

-- If the table was empty, preserve a safe starting setting.
update public.planner_settings
set start_date = coalesce(start_date, date '2026-09-17'),
    allow_weekends = true,
    updated_at = now()
where id = 1;

insert into public.planner_settings(id, start_date, offline_day, allow_weekends, updated_at)
select 1, date '2026-09-17', 0, true, now()
where not exists (select 1 from public.planner_settings where id = 1);

-- Reset/create the default admin as requested.
do $$
begin
  if exists (select 1 from public.admin_config where id = 1) then
    update public.admin_config
    set username = 'admin',
        password_hash = extensions.crypt('admin', extensions.gen_salt('bf')),
        updated_at = now()
    where id = 1;
  else
    insert into public.admin_config(id, username, password_hash, updated_at)
    values (1, 'admin', extensions.crypt('admin', extensions.gen_salt('bf')), now());
  end if;
end $$;

-- ============================================================
-- 3) POLICIES
-- ============================================================

alter table public.subjects enable row level security;
alter table public.courses_v2 enable row level security;
alter table public.study_sessions_v2 enable row level security;
alter table public.planner_settings enable row level security;
alter table public.admin_config enable row level security;
alter table public.admin_sessions enable row level security;

-- Remove old policies created by earlier versions, then recreate only read policies.
do $$
declare
  r record;
begin
  for r in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname='public'
      and tablename in ('subjects','courses_v2','study_sessions_v2','planner_settings','admin_config','admin_sessions')
  loop
    execute format('drop policy if exists %I on %I.%I', r.policyname, r.schemaname, r.tablename);
  end loop;
end $$;

create policy "anon_subjects_select" on public.subjects
for select to anon using (true);

create policy "anon_courses_select" on public.courses_v2
for select to anon using (true);

create policy "anon_sessions_select" on public.study_sessions_v2
for select to anon using (true);

create policy "anon_settings_select" on public.planner_settings
for select to anon using (true);

-- No direct anonymous access to admin data.

-- ============================================================
-- 4) SMALL HELPERS
-- ============================================================

create or replace function public.is_admin_token(p_token text)
returns boolean
language sql
security definer
set search_path = public, pg_catalog
as $$
  select exists (
    select 1
    from public.admin_sessions
    where token = p_token
      and expires_at = 'infinity'::timestamptz
  );
$$;

revoke all on function public.is_admin_token(text) from public;
grant execute on function public.is_admin_token(text) to anon;

create or replace function public.official_offline_isodow(p_date date)
returns integer
language plpgsql
immutable
as $$
declare
  v_monday date := date_trunc('week', p_date)::date;
  v_previous date := v_monday - 7;
  v_day integer;
  v_previous_day integer;
  v_hex text;
begin
  -- Stable pseudo-random weekday, 1..5, based on the week.
  v_hex := md5(v_monday::text);
  v_day := (get_byte(decode(substr(v_hex,1,2),'hex'),0) % 5) + 1;

  v_hex := md5(v_previous::text);
  v_previous_day := (get_byte(decode(substr(v_hex,1,2),'hex'),0) % 5) + 1;

  -- Avoid repeating the same offline weekday in consecutive weeks.
  if v_day = v_previous_day then
    v_day := case when v_day = 5 then 1 else v_day + 1 end;
  end if;

  return v_day;
end;
$$;

revoke all on function public.official_offline_isodow(date) from public;

-- ============================================================
-- 5) ADMIN LOGIN / SESSION
-- ============================================================

create or replace function public.admin_login(p_username text, p_password text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_catalog
as $$
declare
  v_hash text;
  v_token text;
begin
  select password_hash into v_hash
  from public.admin_config
  where id = 1 and username = p_username;

  if v_hash is null or extensions.crypt(coalesce(p_password,''), v_hash) <> v_hash then
    return jsonb_build_object('ok', false);
  end if;

  v_token := encode(extensions.gen_random_bytes(32), 'hex');

  insert into public.admin_sessions(token, expires_at)
  values (v_token, 'infinity'::timestamptz);

  return jsonb_build_object('ok', true, 'token', v_token);
end;
$$;

grant execute on function public.admin_login(text,text) to anon;

create or replace function public.admin_validate_token(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
begin
  if public.is_admin_token(p_token) then
    return jsonb_build_object('ok', true);
  end if;
  return jsonb_build_object('ok', false);
end;
$$;

grant execute on function public.admin_validate_token(text) to anon;

create or replace function public.admin_change_password(p_token text, p_new_password text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions, pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  -- No length, complexity, or character requirements.
  update public.admin_config
  set password_hash = extensions.crypt(coalesce(p_new_password,''), extensions.gen_salt('bf')),
      updated_at = now()
  where id = 1;

  return true;
end;
$$;

grant execute on function public.admin_change_password(text,text) to anon;

-- ============================================================
-- 6) SUBJECTS
-- ============================================================

create or replace function public.admin_create_subject(p_token text, p_name text, p_sort_order integer)
returns bigint
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare v_id bigint;
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;
  if trim(coalesce(p_name,'')) = '' then raise exception 'Le nom de la matière est obligatoire'; end if;

  insert into public.subjects(name, sort_order)
  values (trim(p_name), coalesce(p_sort_order,1))
  returning id into v_id;
  return v_id;
end;
$$;

grant execute on function public.admin_create_subject(text,text,integer) to anon;

create or replace function public.admin_delete_subject(p_token text, p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;
  delete from public.subjects where id = p_id;
  return true;
end;
$$;

grant execute on function public.admin_delete_subject(text,bigint) to anon;

-- ============================================================
-- 7) COURSES
-- ============================================================

create or replace function public.admin_create_course(
  p_token text,
  p_subject_id bigint,
  p_title text,
  p_professor text,
  p_drive_url text,
  p_sort_order integer
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  v_id bigint;
  v_global integer;
  v_sort integer;
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;
  if not exists(select 1 from public.subjects where id=p_subject_id) then raise exception 'Matière introuvable'; end if;
  if trim(coalesce(p_title,'')) = '' then raise exception 'Le nom du cours est obligatoire'; end if;

  select coalesce(max(global_order),0)+1 into v_global from public.courses_v2;
  select coalesce(max(sort_order),0)+1 into v_sort from public.courses_v2 where subject_id=p_subject_id;

  insert into public.courses_v2(subject_id,title,professor,drive_url,sort_order,global_order)
  values(p_subject_id,trim(p_title),nullif(trim(coalesce(p_professor,'')),''),nullif(trim(coalesce(p_drive_url,'')),''),coalesce(p_sort_order,v_sort),v_global)
  returning id into v_id;

  return v_id;
end;
$$;

grant execute on function public.admin_create_course(text,bigint,text,text,text,integer) to anon;

create or replace function public.admin_update_course(
  p_token text,
  p_id bigint,
  p_subject_id bigint,
  p_title text,
  p_professor text,
  p_drive_url text
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;
  update public.courses_v2
  set subject_id=p_subject_id,
      title=trim(p_title),
      professor=nullif(trim(coalesce(p_professor,'')),''),
      drive_url=nullif(trim(coalesce(p_drive_url,'')),'')
  where id=p_id;
  return true;
end;
$$;

grant execute on function public.admin_update_course(text,bigint,bigint,text,text,text) to anon;

create or replace function public.admin_delete_course(p_token text, p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;
  delete from public.courses_v2 where id=p_id;
  return true;
end;
$$;

grant execute on function public.admin_delete_course(text,bigint) to anon;

create or replace function public.admin_move_course(p_token text, p_course_id bigint, p_direction integer)
returns boolean
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  v_current integer;
  v_other_id bigint;
  v_other integer;
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;
  select global_order into v_current from public.courses_v2 where id=p_course_id;
  if v_current is null then raise exception 'Cours introuvable'; end if;

  if p_direction < 0 then
    select id,global_order into v_other_id,v_other
    from public.courses_v2
    where global_order < v_current
    order by global_order desc
    limit 1;
  else
    select id,global_order into v_other_id,v_other
    from public.courses_v2
    where global_order > v_current
    order by global_order asc
    limit 1;
  end if;

  if v_other_id is null then return true; end if;

  update public.courses_v2 set global_order = -global_order where id in (p_course_id,v_other_id);
  update public.courses_v2 set global_order = v_other where id=p_course_id;
  update public.courses_v2 set global_order = v_current where id=v_other_id;
  return true;
end;
$$;

grant execute on function public.admin_move_course(text,bigint,integer) to anon;

-- Remove existing weekend sessions created by the old automatic planner.
-- Weekends will remain empty unless a new session is explicitly added by an admin.
delete from public.study_sessions_v2
where extract(isodow from study_date)::integer in (6,7);

-- ============================================================
-- 8) INTERNAL SCHEDULE REBUILD
-- ============================================================

create or replace function public.rebuild_schedule_internal()
returns integer
language plpgsql
security definer
set search_path = public, extensions, pg_catalog
as $$
declare
  v_start date;
  v_date date;
  v_offline_dow integer;
  v_course record;
  v_days integer;
  v_completed integer;
  v_duration integer;
  v_notes text;
  v_created integer := 0;
begin
  select start_date into v_start from public.planner_settings where id=1;
  v_start := coalesce(v_start, date '2026-09-17');
  v_date := v_start;

  create temp table tmp_course_meta(
    course_id bigint primary key,
    days integer,
    completed_count integer,
    duration_min integer,
    notes text
  ) on commit drop;

  insert into tmp_course_meta(course_id,days,completed_count,duration_min,notes)
  select
    c.id,
    greatest(1, least(30, coalesce(c.planned_days,1))),
    greatest(0, coalesce(sum(case when s.completed then 1 else 0 end),0)),
    greatest(0, coalesce(c.default_duration_min,90)),
    c.default_notes
  from public.courses_v2 c
  left join public.study_sessions_v2 s on s.course_id=c.id
  group by c.id, c.planned_days, c.default_duration_min, c.default_notes;

  delete from public.study_sessions_v2 where true;

  for v_course in
    select id from public.courses_v2 order by global_order nulls last, id
  loop
    select days,completed_count,duration_min,notes
    into v_days,v_completed,v_duration,v_notes
    from tmp_course_meta where course_id=v_course.id;

    v_days := greatest(1,least(30,coalesce(v_days,1)));

    for i in 1..v_days loop
      -- Automatic planning uses weekdays only. Weekends stay empty unless the user manually adds a session.
      while extract(isodow from v_date)::integer > 5 loop
        v_date := v_date + 1;
      end loop;

      if extract(isodow from v_date)::integer = public.official_offline_isodow(v_date) then
        insert into public.study_sessions_v2(course_id,study_date,mode,duration_min,notes,planned_days,completed)
        values(v_course.id,v_date,'offline',coalesce(v_duration,90),v_notes,v_days,i <= least(v_completed,v_days));
      else
        insert into public.study_sessions_v2(course_id,study_date,mode,duration_min,notes,planned_days,completed)
        values(v_course.id,v_date,'online',coalesce(v_duration,90),v_notes,v_days,i <= least(v_completed,v_days));
      end if;
      v_created := v_created + 1;
      v_date := v_date + 1;
    end loop;
  end loop;

  return v_created;
end;
$$;

revoke all on function public.rebuild_schedule_internal() from public;

create or replace function public.admin_rebuild_schedule_by_global_order(p_token text)
returns integer
language plpgsql
security definer
set search_path = public, extensions, pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;
  return public.rebuild_schedule_internal();
end;
$$;

grant execute on function public.admin_rebuild_schedule_by_global_order(text) to anon;

-- ============================================================
-- 9) SESSION FUNCTIONS
-- ============================================================

create or replace function public.admin_create_session_series(
  p_token text,
  p_course_id bigint,
  p_start_date date,
  p_mode text,
  p_duration_min integer,
  p_notes text,
  p_days integer,
  p_completed boolean
)
returns integer
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  v_count integer := 0;
  v_days integer := greatest(1,least(30,coalesce(p_days,1)));
  v_date date := p_start_date;
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;
  if p_mode not in ('online','offline') then raise exception 'Mode invalide'; end if;

  for i in 1..v_days loop
    insert into public.study_sessions_v2(course_id,study_date,mode,duration_min,notes,planned_days,completed)
    values(p_course_id,v_date,p_mode,greatest(0,coalesce(p_duration_min,90)),nullif(trim(coalesce(p_notes,'')),''),v_days,coalesce(p_completed,false));
    v_date := v_date + 1;
    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$$;

grant execute on function public.admin_create_session_series(text,bigint,date,text,integer,text,integer,boolean) to anon;

create or replace function public.admin_update_session(
  p_token text,
  p_id uuid,
  p_course_id bigint,
  p_study_date date,
  p_mode text,
  p_duration_min integer,
  p_notes text,
  p_planned_days integer,
  p_completed boolean
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;
  if p_mode not in ('online','offline') then raise exception 'Mode invalide'; end if;

  update public.study_sessions_v2
  set course_id=p_course_id,
      study_date=p_study_date,
      mode=p_mode,
      duration_min=greatest(0,coalesce(p_duration_min,90)),
      notes=nullif(trim(coalesce(p_notes,'')),''),
      planned_days=greatest(1,coalesce(p_planned_days,1)),
      completed=coalesce(p_completed,false)
  where id=p_id;

  update public.courses_v2
  set planned_days=greatest(1,coalesce(p_planned_days,1)),
      default_duration_min=greatest(0,coalesce(p_duration_min,90)),
      default_notes=nullif(trim(coalesce(p_notes,'')),'')
  where id=p_course_id;

  return true;
end;
$$;

grant execute on function public.admin_update_session(text,uuid,bigint,date,text,integer,text,integer,boolean) to anon;

create or replace function public.admin_delete_session(p_token text, p_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;
  delete from public.study_sessions_v2 where id=p_id;
  return true;
end;
$$;

grant execute on function public.admin_delete_session(text,uuid) to anon;

create or replace function public.admin_resize_course_schedule(
  p_token text,
  p_session_id uuid,
  p_new_days integer,
  p_duration_min integer,
  p_notes text,
  p_completed boolean
)
returns integer
language plpgsql
security definer
set search_path = public, extensions, pg_catalog
as $$
declare
  v_course_id bigint;
  v_new_days integer := greatest(1, least(30, coalesce(p_new_days,1)));
  v_completed integer := 0;
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  select course_id into v_course_id
  from public.study_sessions_v2
  where id = p_session_id;

  if v_course_id is null then
    raise exception 'Séance introuvable';
  end if;

  select count(*) into v_completed
  from public.study_sessions_v2
  where course_id = v_course_id
    and completed = true;

  -- If the edited session is explicitly marked completed, keep at least one completed day.
  if p_completed then
    v_completed := greatest(v_completed, 1);
  end if;

  update public.courses_v2
  set planned_days = v_new_days,
      default_duration_min = greatest(0, coalesce(p_duration_min,90)),
      default_notes = nullif(trim(coalesce(p_notes,'')),'')
  where id = v_course_id;

  if not found then
    raise exception 'Cours introuvable';
  end if;

  return public.rebuild_schedule_internal();
end;
$$;

grant execute on function public.admin_resize_course_schedule(text,uuid,integer,integer,text,boolean) to anon;


-- ============================================================
-- 10) SETTINGS + INITIAL SCHEDULE
-- ============================================================

create or replace function public.admin_save_settings(p_token text, p_start_date date, p_offline_day integer)
returns boolean
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;

  if exists(select 1 from public.planner_settings where id=1) then
    update public.planner_settings
    set start_date=coalesce(p_start_date,start_date),
        offline_day=0,
        allow_weekends=false,
        updated_at=now()
    where id=1;
  else
    insert into public.planner_settings(id,start_date,offline_day,allow_weekends,updated_at)
    values(1,coalesce(p_start_date,date '2026-09-17'),0,true,now());
  end if;
  return true;
end;
$$;

grant execute on function public.admin_save_settings(text,date,integer) to anon;

create or replace function public.admin_seed_initial_schedule(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_catalog
as $$
declare
  v_count integer;
  v_start date;
begin
  if not public.is_admin_token(p_token) then
    return jsonb_build_object('ok',false,'error','Session admin invalide');
  end if;

  if exists(select 1 from public.study_sessions_v2) then
    return jsonb_build_object('ok',true,'created',false,'reason','sessions_exist','count',(select count(*) from public.study_sessions_v2));
  end if;

  v_start := (select start_date from public.planner_settings where id=1);
  v_start := coalesce(v_start,date '2026-09-17');
  v_count := public.rebuild_schedule_internal();

  return jsonb_build_object('ok',true,'created',true,'count',v_count,'start_date',v_start);
end;
$$;

grant execute on function public.admin_seed_initial_schedule(text) to anon;

-- ============================================================
-- 11) CLEAN UP PUBLIC EXECUTION OF INTERNAL HELPERS
-- ============================================================

revoke all on function public.rebuild_schedule_internal() from public;
revoke all on function public.official_offline_isodow(date) from public;

-- ============================================================
-- END
-- ============================================================


-- ============================================================
-- v27 STUDY TIMER
-- ============================================================

create table if not exists public.study_timer_state (
  id integer primary key,
  status text not null default 'idle'
    check (status in ('idle','running','paused')),
  session_id uuid references public.study_sessions_v2(id) on delete set null,
  course_id bigint references public.courses_v2(id) on delete set null,
  started_at timestamptz,
  accumulated_seconds integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.study_time_logs (
  id uuid primary key default gen_random_uuid(),
  session_id uuid references public.study_sessions_v2(id) on delete set null,
  course_id bigint references public.courses_v2(id) on delete set null,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  studied_seconds integer not null default 0,
  page_number integer,
  note text,
  created_at timestamptz not null default now()
);

insert into public.study_timer_state(id,status,accumulated_seconds)
values (1,'idle',0)
on conflict (id) do nothing;

alter table public.study_timer_state enable row level security;
alter table public.study_time_logs enable row level security;

drop policy if exists "anon can view timer state" on public.study_timer_state;
create policy "anon can view timer state"
on public.study_timer_state for select to anon using (true);

drop policy if exists "anon can view time logs" on public.study_time_logs;
create policy "anon can view time logs"
on public.study_time_logs for select to anon using (true);

create or replace function public.admin_timer_start(
  p_token text,
  p_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_catalog
as $$
declare
  v_session public.study_sessions_v2%rowtype;
  v_state public.study_timer_state%rowtype;
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  select * into v_session from public.study_sessions_v2 where id=p_session_id;
  if v_session.id is null then raise exception 'Séance introuvable'; end if;

  select * into v_state from public.study_timer_state where id=1;
  if v_state.status='running' then raise exception 'Un chronomètre est déjà en cours'; end if;

  update public.study_timer_state
  set status='running',
      session_id=v_session.id,
      course_id=v_session.course_id,
      started_at=now(),
      accumulated_seconds=coalesce(v_state.accumulated_seconds,0),
      updated_at=now()
  where id=1;

  return jsonb_build_object('ok',true,'status','running','session_id',v_session.id,'course_id',v_session.course_id);
end;
$$;

grant execute on function public.admin_timer_start(text,uuid) to anon;

create or replace function public.admin_timer_pause(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_catalog
as $$
declare
  v_state public.study_timer_state%rowtype;
  v_add integer:=0;
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;
  select * into v_state from public.study_timer_state where id=1;

  if v_state.status<>'running' then
    return jsonb_build_object('ok',true,'status',v_state.status);
  end if;

  if v_state.started_at is not null then
    v_add:=greatest(0,floor(extract(epoch from (now()-v_state.started_at)))::integer);
  end if;

  update public.study_timer_state
  set status='paused',
      started_at=null,
      accumulated_seconds=coalesce(accumulated_seconds,0)+v_add,
      updated_at=now()
  where id=1;

  return jsonb_build_object('ok',true,'status','paused');
end;
$$;

grant execute on function public.admin_timer_pause(text) to anon;

create or replace function public.admin_timer_resume(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_catalog
as $$
declare
  v_state public.study_timer_state%rowtype;
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;
  select * into v_state from public.study_timer_state where id=1;
  if v_state.session_id is null then raise exception 'Aucune session à reprendre'; end if;

  update public.study_timer_state
  set status='running', started_at=now(), updated_at=now()
  where id=1;

  return jsonb_build_object('ok',true,'status','running');
end;
$$;

grant execute on function public.admin_timer_resume(text) to anon;

create or replace function public.admin_timer_end(
  p_token text,
  p_page_number integer,
  p_note text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_catalog
as $$
declare
  v_state public.study_timer_state%rowtype;
  v_seconds integer:=0;
  v_session_seconds integer:=0;
  v_now timestamptz:=now();
begin
  if not public.is_admin_token(p_token) then raise exception 'Session admin invalide'; end if;
  select * into v_state from public.study_timer_state where id=1;
  if v_state.session_id is null then raise exception 'Aucune session en cours'; end if;

  v_seconds:=coalesce(v_state.accumulated_seconds,0);

  if v_state.status='running' and v_state.started_at is not null then
    v_seconds:=v_seconds+greatest(0,floor(extract(epoch from (v_now-v_state.started_at)))::integer);
  end if;

  insert into public.study_time_logs(
    session_id,course_id,started_at,ended_at,studied_seconds,page_number,note
  )
  values(
    v_state.session_id,
    v_state.course_id,
    coalesce(v_state.started_at,v_now),
    v_now,
    greatest(0,v_seconds),
    p_page_number,
    nullif(trim(coalesce(p_note,'')),'')
  );

  select coalesce(sum(studied_seconds),0)
  into v_session_seconds
  from public.study_time_logs
  where session_id=v_state.session_id;

  update public.study_sessions_v2
  set duration_min=floor(v_session_seconds/60.0)::integer
  where id=v_state.session_id;

  update public.study_timer_state
  set status='idle',
      session_id=null,
      course_id=null,
      started_at=null,
      accumulated_seconds=0,
      updated_at=v_now
  where id=1;

  return jsonb_build_object('ok',true,'studied_seconds',greatest(0,v_seconds),'page_number',p_page_number);
end;
$$;

grant execute on function public.admin_timer_end(text,integer,text) to anon;

-- Existing manual durations are no longer used by the UI.
-- Keep already logged timer durations; otherwise reset old default minutes to 0.
update public.study_sessions_v2 s
set duration_min=0
where not exists (
  select 1 from public.study_time_logs l where l.session_id=s.id
);

-- ============================================================
-- END v27 STUDY TIMER
-- ============================================================


-- v31: safely ensure every course has at least one session.
-- No existing session is deleted or modified.
create or replace function public.admin_ensure_course_coverage(p_token text)
returns jsonb
language plpgsql
security definer
set search_path=public,extensions,pg_catalog
as $$
declare
  v_added integer:=0;
  v_date date;
  v_course record;
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  select coalesce(
    max(study_date),
    (select start_date from public.planner_settings where id=1),
    date '2026-09-17'
  )
  into v_date
  from public.study_sessions_v2;

  v_date:=v_date+1;

  for v_course in
    select c.id
    from public.courses_v2 c
    where not exists (
      select 1 from public.study_sessions_v2 s where s.course_id=c.id
    )
    order by c.global_order nulls last, c.sort_order, c.id
  loop
    while extract(isodow from v_date)::integer in (6,7) loop
      v_date:=v_date+1;
    end loop;

    insert into public.study_sessions_v2(
      course_id,study_date,mode,duration_min,notes,planned_days,completed
    )
    values(
      v_course.id,
      v_date,
      case when extract(isodow from v_date)::integer=3 then 'offline' else 'online' end,
      0,null,1,false
    );

    v_added:=v_added+1;
    v_date:=v_date+1;
  end loop;

  return jsonb_build_object('ok',true,'added',v_added);
end;
$$;

grant execute on function public.admin_ensure_course_coverage(text) to anon;


-- ============================================================
-- v33 DAY OFF
-- ============================================================

create table if not exists public.planner_day_offs (
  off_date date primary key,
  created_at timestamptz not null default now()
);

alter table public.planner_day_offs enable row level security;

drop policy if exists "anon can view day offs"
on public.planner_day_offs;
create policy "anon can view day offs"
on public.planner_day_offs
for select to anon
using (true);

create or replace function public.admin_add_day_off(
  p_token text,
  p_off_date date
)
returns jsonb
language plpgsql
security definer
set search_path=public,extensions,pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  insert into public.planner_day_offs(off_date)
  values(p_off_date)
  on conflict (off_date) do nothing;

  return jsonb_build_object('ok',true,'off_date',p_off_date);
end;
$$;

grant execute on function public.admin_add_day_off(text,date) to anon;

create or replace function public.admin_remove_day_off(
  p_token text,
  p_off_date date
)
returns jsonb
language plpgsql
security definer
set search_path=public,extensions,pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  delete from public.planner_day_offs
  where off_date=p_off_date;

  return jsonb_build_object('ok',true,'off_date',p_off_date);
end;
$$;

grant execute on function public.admin_remove_day_off(text,date) to anon;

-- ============================================================
-- END v33 DAY OFF
-- ============================================================


-- ============================================================
-- v34: DAY OFF DATES
-- ============================================================

create table if not exists public.planner_day_offs (
  off_date date primary key,
  created_at timestamptz not null default now()
);

alter table public.planner_day_offs enable row level security;

drop policy if exists "anon can view day offs" on public.planner_day_offs;
create policy "anon can view day offs"
on public.planner_day_offs
for select to anon
using (true);

create or replace function public.admin_add_day_off(
  p_token text,
  p_off_date date
)
returns jsonb
language plpgsql
security definer
set search_path=public,extensions,pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  insert into public.planner_day_offs(off_date)
  values(p_off_date)
  on conflict (off_date) do nothing;

  return jsonb_build_object('ok',true,'off_date',p_off_date);
end;
$$;

grant execute on function public.admin_add_day_off(text,date) to anon;

create or replace function public.admin_remove_day_off(
  p_token text,
  p_off_date date
)
returns jsonb
language plpgsql
security definer
set search_path=public,extensions,pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  delete from public.planner_day_offs where off_date=p_off_date;

  return jsonb_build_object('ok',true,'off_date',p_off_date);
end;
$$;

grant execute on function public.admin_remove_day_off(text,date) to anon;

-- ============================================================
-- END v34 DAY OFF
-- ============================================================


-- ============================================================

-- ============================================================
-- v38 DAY-OFF SHIFT
-- When an admin marks a date as Day Off:
--   * the selected date is stored as a Day Off;
--   * all NON-COMPLETED sessions from that date onward are shifted
--     one available study day forward, preserving each day's group;
--   * completed history is never moved;
--   * other Day Off dates and weekends are skipped.
-- Removing Day Off only removes the marker; it does not rewrite history.
-- ============================================================

create table if not exists public.planner_day_offs (
  off_date date primary key,
  created_at timestamptz not null default now()
);

alter table public.planner_day_offs enable row level security;

drop policy if exists "anon can view day offs"
on public.planner_day_offs;

create policy "anon can view day offs"
on public.planner_day_offs
for select
to anon
using (true);

create or replace function public.admin_add_day_off_shift(
  p_token text,
  p_off_date date
)
returns jsonb
language plpgsql
security definer
set search_path=public,extensions,pg_catalog
as $$
declare
  v_date date;
  v_target date;
  v_groups integer:=0;
  v_group record;
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  insert into public.planner_day_offs(off_date)
  values(p_off_date)
  on conflict(off_date) do nothing;

  -- Process from latest date to earliest date. This prevents a shift
  -- from colliding with a later uncompleted group that still needs moving.
  for v_group in
    select study_date
    from public.study_sessions_v2
    where study_date >= p_off_date
      and completed=false
    group by study_date
    order by study_date desc
  loop

    v_date:=v_group.study_date;
    v_target:=v_date+1;

    while extract(isodow from v_target)::integer in (6,7)
       or exists(
         select 1
         from public.planner_day_offs d
         where d.off_date=v_target
       )
    loop
      v_target:=v_target+1;
    end loop;

    update public.study_sessions_v2
    set study_date=v_target
    where study_date=v_date
      and completed=false;

    v_groups:=v_groups+1;
  end loop;

  return jsonb_build_object(
    'ok',true,
    'off_date',p_off_date,
    'shifted_groups',v_groups
  );
end;
$$;

grant execute
on function public.admin_add_day_off_shift(text,date)
to anon;

create or replace function public.admin_remove_day_off_shift(
  p_token text,
  p_off_date date
)
returns jsonb
language plpgsql
security definer
set search_path=public,extensions,pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  delete from public.planner_day_offs
  where off_date=p_off_date;

  return jsonb_build_object(
    'ok',true,
    'off_date',p_off_date
  );
end;
$$;

grant execute
on function public.admin_remove_day_off_shift(text,date)
to anon;

-- ============================================================
-- END v38 DAY-OFF SHIFT
-- ============================================================


-- ============================================================
-- v39 UNDO / HISTORY FOR PLANNER CHANGES
-- Records planning/session/Day-Off changes without touching
-- study_time_logs. Undo restores sessions and Day-Off dates.
-- ============================================================

create table if not exists public.planner_change_history (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  label text not null,
  before_state jsonb not null,
  after_state jsonb not null,
  undone_at timestamptz
);

alter table public.planner_change_history enable row level security;

-- No direct anon insert/update/delete policy: only SECURITY DEFINER RPCs handle history.

create or replace function public._planner_snapshot()
returns jsonb
language sql
security definer
set search_path=public,pg_catalog
as $$
  select jsonb_build_object(
    'sessions',
      coalesce(
        (select jsonb_agg(to_jsonb(s) order by s.id) from public.study_sessions_v2 s),
        '[]'::jsonb
      ),
    'dayoffs',
      coalesce(
        (select jsonb_agg(to_jsonb(d) order by d.off_date) from public.planner_day_offs d),
        '[]'::jsonb
      )
  );
$$;

create or replace function public.admin_get_planner_snapshot(
  p_token text
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;
  return public._planner_snapshot();
end;
$$;

grant execute on function public.admin_get_planner_snapshot(text) to anon;

create or replace function public.admin_record_planner_action(
  p_token text,
  p_label text,
  p_before_state jsonb,
  p_after_state jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_catalog
as $$
declare
  v_id bigint;
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  -- If nothing actually changed, don't create an undo entry.
  if p_before_state = p_after_state then
    return jsonb_build_object('ok',true,'recorded',false);
  end if;

  insert into public.planner_change_history(label,before_state,after_state)
  values(coalesce(nullif(trim(p_label),''),'Modification du planning'),p_before_state,p_after_state)
  returning id into v_id;

  return jsonb_build_object('ok',true,'recorded',true,'id',v_id);
end;
$$;

grant execute on function public.admin_record_planner_action(text,text,jsonb,jsonb) to anon;

create or replace function public.admin_undo_status(
  p_token text
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_catalog
as $$
declare
  v_row public.planner_change_history%rowtype;
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  select *
  into v_row
  from public.planner_change_history
  where undone_at is null
  order by id desc
  limit 1;

  if v_row.id is null then
    return jsonb_build_object('can_undo',false,'label',null);
  end if;

  return jsonb_build_object(
    'can_undo',true,
    'label',v_row.label,
    'id',v_row.id
  );
end;
$$;

grant execute on function public.admin_undo_status(text) to anon;

create or replace function public.admin_undo_last_planner_action(
  p_token text
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_catalog
as $$
declare
  v_row public.planner_change_history%rowtype;
  v_current jsonb;
  v_before jsonb;
  v_after jsonb;
  v_id uuid;
  v_json jsonb;
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  select *
  into v_row
  from public.planner_change_history
  where undone_at is null
  order by id desc
  limit 1
  for update;

  if v_row.id is null then
    return jsonb_build_object('ok',false,'message','Aucune modification à annuler.');
  end if;

  v_current:=public._planner_snapshot();

  -- Do not silently overwrite a newer change made by another client.
  if v_current <> v_row.after_state then
    raise exception 'Le planning a changé depuis cette modification. Annulation interrompue pour protéger les données.';
  end if;

  v_before:=v_row.before_state;
  v_after:=v_row.after_state;

  -- Restore Day Off dates exactly as they were.
  delete from public.planner_day_offs where true;

  insert into public.planner_day_offs(off_date,created_at)
  select
    (x->>'off_date')::date,
    coalesce((x->>'created_at')::timestamptz,now())
  from jsonb_array_elements(coalesce(v_before->'dayoffs','[]'::jsonb)) x
  on conflict(off_date) do nothing;

  -- Restore existing sessions in place. This preserves UUIDs and time-log links.
  for v_json in
    select value
    from jsonb_array_elements(coalesce(v_before->'sessions','[]'::jsonb))
  loop
    v_id:=(v_json->>'id')::uuid;

    update public.study_sessions_v2
    set course_id=(v_json->>'course_id')::bigint,
        study_date=(v_json->>'study_date')::date,
        mode=v_json->>'mode',
        duration_min=coalesce((v_json->>'duration_min')::integer,0),
        notes=v_json->>'notes',
        planned_days=coalesce((v_json->>'planned_days')::integer,1),
        completed=coalesce((v_json->>'completed')::boolean,false)
    where id=v_id;

    if not found then
      insert into public.study_sessions_v2(
        id,course_id,study_date,mode,duration_min,notes,planned_days,completed,created_at
      )
      values(
        v_id,
        (v_json->>'course_id')::bigint,
        (v_json->>'study_date')::date,
        v_json->>'mode',
        coalesce((v_json->>'duration_min')::integer,0),
        v_json->>'notes',
        coalesce((v_json->>'planned_days')::integer,1),
        coalesce((v_json->>'completed')::boolean,false),
        coalesce((v_json->>'created_at')::timestamptz,now())
      );
    end if;
  end loop;

  -- Remove sessions created by the action, but never remove a session
  -- that already has a time log.
  for v_json in
    select value
    from jsonb_array_elements(coalesce(v_after->'sessions','[]'::jsonb))
    where not exists (
      select 1
      from jsonb_array_elements(coalesce(v_before->'sessions','[]'::jsonb)) b
      where b->>'id'=value->>'id'
    )
  loop
    v_id:=(v_json->>'id')::uuid;

    if exists(select 1 from public.study_time_logs l where l.session_id=v_id) then
      raise exception 'Cette séance possède déjà un enregistrement de chrono. Annulation refusée pour protéger le temps étudié.';
    end if;

    delete from public.study_sessions_v2
    where id=v_id;
  end loop;

  update public.planner_change_history
  set undone_at=now()
  where id=v_row.id;

  return jsonb_build_object(
    'ok',true,
    'id',v_row.id,
    'label',v_row.label
  );
end;
$$;

grant execute on function public.admin_undo_last_planner_action(text) to anon;

-- ============================================================
-- END v39 UNDO
-- ============================================================


-- ============================================================

-- ============================================================

-- ============================================================
-- v43 SAFE FINAL SCHEDULING LAYER
-- ============================================================

-- 1) Reorder only FUTURE / incomplete sessions.
--    It never deletes sessions and never changes completed history.
create or replace function public.rebuild_schedule_internal()
returns integer
language plpgsql
security definer
set search_path = public,extensions,pg_catalog
as $$
declare
  v_start date;
  v_cursor date;
  v_count integer := 0;
  v_row record;
begin
  select coalesce(start_date,date '2026-09-17')
  into v_start
  from public.planner_settings
  where id=1;

  v_cursor := greatest(
    v_start,
    coalesce(
      (select max(study_date)+1 from public.study_sessions_v2 where completed=true),
      v_start
    )
  );

  for v_row in
    select s.id
    from public.study_sessions_v2 s
    join public.courses_v2 c on c.id=s.course_id
    where s.completed=false
    order by c.global_order nulls last, c.id, s.study_date, s.id
  loop
    while extract(isodow from v_cursor)::integer in (6,7)
       or exists(
         select 1
         from public.planner_day_offs d
         where d.off_date=v_cursor
       )
    loop
      v_cursor := v_cursor + 1;
    end loop;

    update public.study_sessions_v2
    set study_date=v_cursor
    where id=v_row.id;

    v_cursor := v_cursor + 1;
    v_count := v_count + 1;
  end loop;

  return v_count;
end;
$$;

revoke all on function public.rebuild_schedule_internal() from public;

-- 2) Public admin reorder action used by ↑/↓.
create or replace function public.admin_rebuild_schedule_by_global_order(
  p_token text
)
returns integer
language plpgsql
security definer
set search_path = public,extensions,pg_catalog
as $$
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  return public.rebuild_schedule_internal();
end;
$$;

grant execute
on function public.admin_rebuild_schedule_by_global_order(text)
to anon;

-- 3) Resize a course safely.
--    - Updates the requested course's planned days.
--    - Preserves completed days.
--    - Adds missing future sessions when needed.
--    - Removes only future sessions without timer logs.
--    - Reorders future sessions without deleting the rest.
create or replace function public.admin_resize_course_schedule(
  p_token text,
  p_session_id uuid,
  p_new_days integer,
  p_duration_min integer,
  p_notes text,
  p_completed boolean
)
returns integer
language plpgsql
security definer
set search_path = public,extensions,pg_catalog
as $$
declare
  v_course_id bigint;
  v_new_days integer := greatest(1,least(30,coalesce(p_new_days,1)));
  v_completed_count integer;
  v_incomplete_count integer;
  v_needed integer;
  v_extra integer;
  v_date date;
  v_i integer;
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  select course_id
  into v_course_id
  from public.study_sessions_v2
  where id=p_session_id;

  if v_course_id is null then
    raise exception 'Séance introuvable';
  end if;

  -- Update the edited session itself.
  update public.study_sessions_v2
  set completed=coalesce(p_completed,false),
      notes=nullif(trim(coalesce(p_notes,'')),''),
      planned_days=v_new_days,
      duration_min=greatest(0,coalesce(p_duration_min,0))
  where id=p_session_id;

  update public.courses_v2
  set planned_days=v_new_days,
      default_duration_min=greatest(0,coalesce(p_duration_min,0)),
      default_notes=nullif(trim(coalesce(p_notes,'')),'')
  where id=v_course_id;

  select count(*)
  into v_completed_count
  from public.study_sessions_v2
  where course_id=v_course_id
    and completed=true;

  select count(*)
  into v_incomplete_count
  from public.study_sessions_v2
  where course_id=v_course_id
    and completed=false;

  v_needed:=greatest(0,v_new_days-v_completed_count);

  -- Add missing future sessions.
  if v_incomplete_count < v_needed then
    v_extra:=v_needed-v_incomplete_count;

    select coalesce(max(study_date)+1, current_date+1)
    into v_date
    from public.study_sessions_v2;

    for v_i in 1..v_extra loop
      insert into public.study_sessions_v2(
        course_id,study_date,mode,duration_min,notes,planned_days,completed
      )
      values(
        v_course_id,
        v_date,
        case
          when extract(isodow from v_date)::integer=3 then 'offline'
          else 'online'
        end,
        0,
        nullif(trim(coalesce(p_notes,'')),''),
        v_new_days,
        false
      );
      v_date:=v_date+1;
    end loop;
  end if;

  -- Remove surplus future sessions only if they have NO timer log.
  if v_incomplete_count > v_needed then
    v_extra:=v_incomplete_count-v_needed;

    delete from public.study_sessions_v2 s
    where s.id in (
      select s2.id
      from public.study_sessions_v2 s2
      where s2.course_id=v_course_id
        and s2.completed=false
        and not exists(
          select 1
          from public.study_time_logs l
          where l.session_id=s2.id
        )
      order by s2.study_date desc, s2.id desc
      limit v_extra
    );
  end if;

  -- If logged sessions prevent pruning, do not delete them.
  return public.rebuild_schedule_internal();
end;
$$;

grant execute
on function public.admin_resize_course_schedule(text,uuid,integer,integer,text,boolean)
to anon;

-- 4) Initial seed: only when there are truly no sessions.
create or replace function public.admin_seed_initial_schedule(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public,extensions,pg_catalog
as $$
declare
  v_start date;
  v_cursor date;
  v_created integer:=0;
  v_course record;
  v_days integer;
  v_i integer;
begin
  if not public.is_admin_token(p_token) then
    return jsonb_build_object('ok',false,'error','Session admin invalide');
  end if;

  if exists(select 1 from public.study_sessions_v2) then
    return jsonb_build_object(
      'ok',true,
      'created',false,
      'reason','sessions_exist',
      'count',(select count(*) from public.study_sessions_v2)
    );
  end if;

  select coalesce(start_date,date '2026-09-17')
  into v_start
  from public.planner_settings
  where id=1;

  v_cursor:=v_start;

  for v_course in
    select id, greatest(1,least(30,coalesce(planned_days,1))) as planned_days
    from public.courses_v2
    order by global_order nulls last,id
  loop
    v_days:=v_course.planned_days;

    for v_i in 1..v_days loop
      while extract(isodow from v_cursor)::integer in (6,7)
         or exists(
           select 1 from public.planner_day_offs d where d.off_date=v_cursor
         )
      loop
        v_cursor:=v_cursor+1;
      end loop;

      insert into public.study_sessions_v2(
        course_id,study_date,mode,duration_min,notes,planned_days,completed
      )
      values(
        v_course.id,
        v_cursor,
        case
          when extract(isodow from v_cursor)::integer=official_offline_isodow(v_cursor)
            then 'offline'
          else 'online'
        end,
        0,
        null,
        v_days,
        false
      );

      v_created:=v_created+1;
      v_cursor:=v_cursor+1;
    end loop;
  end loop;

  return jsonb_build_object(
    'ok',true,
    'created',true,
    'count',v_created,
    'start_date',v_start
  );
end;
$$;

grant execute
on function public.admin_seed_initial_schedule(text)
to anon;

-- 5) Safe "restore original order".
--    IMPORTANT: it does not delete sessions or rebuild completed history.
create or replace function public.admin_restore_original_order(
  p_token text
)
returns jsonb
language plpgsql
security definer
set search_path=public,extensions,pg_catalog
as $$
declare
  v_start date;
  v_count integer;
begin
  if not public.is_admin_token(p_token) then
    raise exception 'Session admin invalide';
  end if;

  select coalesce(start_date,date '2026-09-17')
  into v_start
  from public.planner_settings
  where id=1;

  with ranked as(
    select
      c.id,
      row_number() over(
        order by
          case
            when lower(coalesce(c.professor,'')) like '%saadi%' then 1
            when lower(coalesce(c.professor,'')) like '%mimouni%' then 2
            when lower(coalesce(c.professor,'')) like '%tahiri%' then 3
            else 4
          end,
          c.sort_order,
          c.id
      ) as rn
    from public.courses_v2 c
  )
  update public.courses_v2 c
  set global_order=r.rn
  from ranked r
  where c.id=r.id;

  -- Reset future Day Off markers without touching historical dates.
  delete from public.planner_day_offs
  where off_date>=v_start;

  -- Reorder existing incomplete sessions only.
  v_count:=public.rebuild_schedule_internal();

  return jsonb_build_object(
    'ok',true,
    'reordered_sessions',v_count,
    'message','Ordre Saadi → Mimouni → Tahiri restauré; progression conservée.'
  );
end;
$$;

grant execute
on function public.admin_restore_original_order(text)
to anon;

-- ============================================================
-- END v43 SAFE FINAL SCHEDULING LAYER
-- ============================================================
